// src/constants/questions.js
export const EXTENDED_QUESTIONS = [
  { number: 1, question: "Are you more of a cat person or a dog person?", type: "MC", label: "cat_dog", options: ["Cat person", "Dog person"] },
  { number: 2, question: "Star Wars or Star Trek?", type: "MC", label: "StarWars_StarTrek", options: ["Star Wars", "Star Trek"] },
  { number: 3, question: "What color are your eyes?", type: "MC", label: "eye_color", options: ["Blue", "Brown", "Gray", "Green", "Hazel"] },
  { number: 4, question: "How many novels have you read in the last year?", type: "MC", label: "novels_read", options: ["0-2", "3-5", "6-10", "More than 10"] },
  { number: 5, question: "Which mathematics conference would you most likely be found at?", type: "MC", label: "math_conference", options: ["NCTM", "ICOTS", "SRTL", "ASA"] },
  { number: 6, question: "Which of the following would you say is your primary occupation?", type: "MC", label: "professional_cat", options: ["Researcher", "Educator", "Software developer", "Entrepreneur/Consultant", "Student"] },
  { number: 7, question: "How would you primarily characterize your personality tendency?", type: "MC", label: "intro_extrovert", options: ["Introvert", "Extrovert", "Ambivert (combines traits of both)"] },
  { number: 8, question: "What would people be most likely to find you teaching?", type: "MC", label: "teaching_subj", options: ["Mathematics", "Pre-service teaching", "Statistics", "Science", "Other/None"] },
  { number: 9, question: "What did you use to complete your first major class paper?", type: "MC", label: "paper_writing", options: ["Pencil and paper", "Manual typewriter", "Electric typewriter", "Dot matrix printer", "Laser printer"] },
  { number: 10, question: "Which pizza topping do you prefer?", type: "MC", label: "pizza_topping", options: ["Cheese", "Pepperoni", "Sausage", "Veggie"] },
  { number: 11, question: "What was the magnitude of the largest earthquake you've experienced?", type: "MC", label: "earthquake_mag", options: ["0-2", "2-4", "4-5", "5-6", "6-7"] },
  { number: 12, question: "In a waiting room, what magazine are you most likely to pick up and read?", type: "MC", label: "magazine_read", options: ["Better Homes and Gardens", "Game Informer", "People", "Nationall Geographic", "The Economist"] },
  { number: 13, question: "When is your birthday?", type: "MC", label: "birthday_month", options: ["January/February", "March/April", "May/June", "July/August", "September/October", "November/December"] },
  { number: 14, question: "What was the first email client you ever used?", type: "MC", label: "email_client", options: ["Elm/Pine", "Eudora", "Outlook", "Hotmail", "Yahoo", "Gmail"] },
  { number: 15, question: "How many movies did you see in the theater last year?", type: "MC", label: "movies_theater", options: ["0-2", "3-4", "5-10", "10-20", "20+"] },
  { number: 16, question: "To which gender identity do you most identify?", type: "MC", label: "gender", options: ["Male", "Female", "Gender diverse"] },
  { number: 17, question: "Where did you grow up?", type: "MC", label: "region_youth", options: ["Northeast", "Midwest", "South", "West", "Outside the US"] },
  { number: 18, question: "Where do you live currently?", type: "MC", label: "region_current", options: ["Northeast", "Midwest", "South", "West", "Outside the US"] },
  { number: 19, question: "Which beverage would you prefer to drink in the morning?", type: "MC", label: "am_beverage", options: ["Good coffee", "Any old coffee", "Tea", "Juice", "Soda"] },
  { number: 20, question: "How many siblings do you have?", type: "MC", label: "siblings", options: ["0 siblings", "1 sibling", "2 siblings", "3 siblings", "4 or more siblings"] },
  { number: 21, question: "Which best describes your current living scenario?", type: "MC", label: "living_scenario", options: ["Apartment with self / family", "House with self / family", "Shared living – apartment", "Shared living – house"] },
  { number: 22, question: "How would you classify the community you live in?", type: "MC", label: "community", options: ["Central city", "Inner suburbs", "Outer suburbs", "Between suburbs and rural", "Rural"] },
  { number: 23, question: "Which kind of fiction books do you like best?", type: "MC", label: "fiction_type", options: ["Fantasy", "Science Fiction", "Romance", "Mystery", "Historical drama"] },
  { number: 24, question: "How many televisions are in your house?", type: "NM", label: "TVs", options: [] },
  { number: 25, question: "How many pets do you have?", type: "NM", label: "pets", options: [] },
  { number: 26, question: "How many miles is your daily commute?", type: "NM", label: "commute_miles", options: [] },
  { number: 27, question: "How many hours is your daily commute?", type: "NM", label: "commute_hrs", options: [] },
  { number: 28, question: "What time do you go to bed during the week?", type: "NM", label: "bedtime", options: [] },
  { number: 29, question: "How many grandchildren do you have?", type: "NM", label: "grandchildren", options: [] },
  { number: 30, question: "How many operas have you seen?", type: "NM", label: "operas_seen", options: [] },
  { number: 31, question: "How many mpg does your car get?", type: "NM", label: "car_mpg", options: [] },
  { number: 32, question: "How many email messages did you get yesterday?", type: "NM", label: "email", options: [] },
  { number: 33, question: "What’s your favorite flavor of ice cream?", type: "OP", label: "ice_cream", options: [] },
  { number: 34, question: "What’s your favorite hobby?", type: "OP", label: "hobby", options: [] },
  { number: 35, question: "What’s your mother’s first name?", type: "OP", label: "mother_name", options: [] },
  { number: 36, question: "What’s your favorite kind of vacation?", type: "OP", label: "vacation_type", options: [] },
  { number: 37, question: "Complete this sentence: “Nobody here knows that I…”", type: "OP", label: "nobody_knows", options: [] },
];

